modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GPL 3.0"
issueTrackerURL="https://github.com/Tourmi/mc-server-side-vein-miner/issues/" #optional
[[mods]] #mandatory
modId="svmm" #mandatory
version="${global.mcVersion}-${file.jarVersion}" #mandatory
displayName="Server-side Vein Miner" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/server-side-vein-miner/" #optional
logoFile="svmm-icon.png" #optional
authors="Tourmi" #optional
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
displayTest="IGNORE_SERVER_VERSION"

description='''
Server-side Vein Miner. Allows one to instantly mine ore veins on a server, without having the mod installed
'''
[[dependencies.svmm]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.svmm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="SERVER"
