modLoader="javafml"
loaderVersion="[$forge_min_version,$forge_max_version)"
license="$mod_license"
issueTrackerURL="$mod_issue_tracker"
[[mods]]
modId="$mod_id"
version="$version"
displayName="$mod_name"
updateJSONURL="$forge_update_json_url"
displayURL="$mod_url"
logoFile="icon.png"
authors="$author_name"
displayTest="$forge_displaytest_value"
credits="$mod_credits"
description="$mod_description"

[[dependencies.$mod_id]]
    modId="minecraft"
    mandatory=true
    versionRange="[$minecraft_min_version,$minecraft_max_version)"
    ordering="NONE"
    side="$forge_minecraft_side"
