name: build

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - uses: christian-draeger/read-properties@1.1.1
      id: java_version
      name: Read Java version
      with:
        path: './gradle.properties'
        properties: 'java_version'
    
    - name: Set up JDK ${{ steps.java_version.outputs.java_version }}
      uses: actions/setup-java@v4
      with:
        java-version: '${{ steps.java_version.outputs.java_version }}'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        name: build-artifact
        path: build/libs/svmm-*.jar
        
