name: Create release

on:
  workflow_dispatch:
    inputs:
      mod-version:
        required: true
        type: string

jobs:
  release-versions:
    strategy:
      fail-fast: false
      matrix:
        minecraft-version: [1.19.2, 1.20.1, 1.21]
    uses: ./.github/workflows/createReleaseForMinecraftVersion.yml
    with:
      minecraft-version: ${{matrix.minecraft-version}}
      mod-version: ${{inputs.mod-version}}
    secrets:
      token-github: ${{ secrets.GITHUB_TOKEN }}
