name: Create release

on:
  workflow_dispatch:
    inputs:
      mod-version:
        required: true
        type: string

jobs:
  release-versions:
    strategy:
      matrix:
        minecraft-version: [1.19.2, 1.20.1]
    uses: ./.github/workflows/createReleaseForMinecraftVersion.yml
    with:
      minecraft-version: ${{matrix.minecraft-version}}
      mod-version: ${{inputs.mod-version}}
    secrets:
      token-github: ${{ secrets.GITHUB_TOKEN }}

  bump-main-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    if: ${{ always() }}
    needs: release-versions
    steps:
    - uses: actions/checkout@v4
      name: Checking out main
      with:
        ref: main
    
    - uses: Reedyuk/write-properties@1.0.3
      name: Update version number
      with:
        path: './gradle.properties'
        property: mod_version
        value: ${{inputs.mod-version}}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
    
    - name: Commit new version to main
      run: |
        git config --global user.name '${{ vars.BUILD_ACTOR_NAME }}'
        git config --global user.email '${{ vars.BUILD_ACTOR_EMAIL }}'
        git add gradle.properties
        git commit -m "Bump main version to ${{ inputs.mod-version }}"
        git push
