name: Update branch from main

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      token-github:
        required: true

jobs:
  update-branch:
    name: update branch ${{ inputs.branch }} from main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Checking out ${{ inputs.branch }}
      with:
        ref: ${{ inputs.branch }}
    
    - name: Merge main into ${{inputs.branch}}
      run: |
        git config --global user.name '${{ vars.BUILD_ACTOR_NAME }}'
        git config --global user.email '${{ vars.BUILD_ACTOR_EMAIL }}'
        git merge --no-ff --no-commit main
        git reset HEAD gradle.properties
        git checkout -- gradle.properties
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build

    - name: Commit and push merge
      run: |
        git commit -m "Merged main in branch"
        git push
